"""init

Revision ID: aea6a0c2d078
Revises: 
Create Date: 2025-08-26 09:19:15.850021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea6a0c2d078'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribuicao_historica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('sheet', sa.String(length=20), nullable=True),
    sa.Column('ordem_geral', sa.Integer(), nullable=True),
    sa.Column('analista', sa.String(length=80), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('interessado', sa.String(length=200), nullable=True),
    sa.Column('assunto', sa.String(length=100), nullable=True),
    sa.Column('setor_origem', sa.String(length=100), nullable=True),
    sa.Column('tipo_processo', sa.String(length=20), nullable=True),
    sa.Column('data_distribuicao', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distribuicao_historica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distribuicao_historica_analista'), ['analista'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribuicao_historica_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribuicao_historica_assunto'), ['assunto'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribuicao_historica_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribuicao_historica_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribuicao_historica_setor_origem'), ['setor_origem'], unique=False)
        batch_op.create_index(batch_op.f('ix_distribuicao_historica_tipo_processo'), ['tipo_processo'], unique=False)

    op.create_table('historico_planilha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=True),
    sa.Column('dados', sa.Text(), nullable=False),
    sa.Column('chave_processo', sa.String(length=120), nullable=True),
    sa.Column('analista_primeiro_nome', sa.String(length=80), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico_planilha', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_planilha_analista_primeiro_nome'), ['analista_primeiro_nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_historico_planilha_chave_processo'), ['chave_processo'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primeiro_nome', sa.String(length=80), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('primeiro_nome')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('entidade', sa.String(length=50), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=30), nullable=True),
    sa.Column('dif_json', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('prioridade', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('setor', sa.String(length=50), nullable=True),
    sa.Column('assunto', sa.String(length=100), nullable=True),
    sa.Column('setor_origem', sa.String(length=100), nullable=True),
    sa.Column('tipo_processo', sa.String(length=20), nullable=True),
    sa.Column('data_distribuicao', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('gerente_id', sa.Integer(), nullable=True),
    sa.Column('analista_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_atribuicao', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analista_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['gerente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processos')
    op.drop_table('auditoria')
    op.drop_table('usuarios')
    with op.batch_alter_table('historico_planilha', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_planilha_chave_processo'))
        batch_op.drop_index(batch_op.f('ix_historico_planilha_analista_primeiro_nome'))

    op.drop_table('historico_planilha')
    with op.batch_alter_table('distribuicao_historica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distribuicao_historica_tipo_processo'))
        batch_op.drop_index(batch_op.f('ix_distribuicao_historica_setor_origem'))
        batch_op.drop_index(batch_op.f('ix_distribuicao_historica_numero'))
        batch_op.drop_index(batch_op.f('ix_distribuicao_historica_mes'))
        batch_op.drop_index(batch_op.f('ix_distribuicao_historica_assunto'))
        batch_op.drop_index(batch_op.f('ix_distribuicao_historica_ano'))
        batch_op.drop_index(batch_op.f('ix_distribuicao_historica_analista'))

    op.drop_table('distribuicao_historica')
    # ### end Alembic commands ###
